"""lsp/tools.py — Facade, re-exports from sub-modules."""
from __future__ import annotations

from .tools_core import (
    CODE_CALL_HIERARCHY_SCHEMA,
    CODE_CALLEES_SCHEMA,
    CODE_CALLERS_SCHEMA,
    CODE_DEFINITION_SCHEMA,
    CODE_DIAGNOSTICS_SCHEMA,
    CODE_DOCUMENT_SYMBOLS_SCHEMA,
    CODE_HIGHLIGHT_SCHEMA,
    CODE_INLAY_HINTS_SCHEMA,
    CODE_REFERENCES_SCHEMA,
    CODE_TYPE_HIERARCHY_SCHEMA,
    _ast_fallback_callees,
    _ast_fallback_definition,
    _ast_fallback_diagnostics,
    _ast_fallback_references,
    _auto_detect_identifier_column,
    _auto_detect_paren_column,
    _build_unused_import_diags,
    _extract_identifier,
    _extract_python_callees,
    _extract_ts_callees,
    _fallback_reference_callers,
    _format_definitions,
    _format_diagnostics_result,
    _format_references,
    _import_detect_language,
    _pull_lsp_diagnostics,
    _python_ast_analyze,
    _read_file_safe,
    _resolve_target_and_lang,
    _rg_search,
    _try_lsp_callers,
    _tsjs_import_heuristic,
    code_call_hierarchy_tool,
    code_callees_tool,
    code_callers_tool,
    code_definition_tool,
    code_diagnostics_tool,
    code_document_symbols_tool,
    code_highlight_tool,
    code_inlay_hints_tool,
    code_references_tool,
    code_type_hierarchy_tool,
)
from .tools_extra import (
    CODE_ACTION_SCHEMA,
    CODE_CODE_LENS_SCHEMA,
    CODE_COMPLETION_SCHEMA,
    CODE_DOCUMENT_LINKS_SCHEMA,
    CODE_FOLDING_RANGE_SCHEMA,
    CODE_IMPLEMENTATIONS_SCHEMA,
    CODE_INLINE_VALUES_SCHEMA,
    CODE_LINKED_EDITING_SCHEMA,
    CODE_PREPARE_RENAME_SCHEMA,
    CODE_SELECTION_RANGE_SCHEMA,
    CODE_SEMANTIC_TOKENS_SCHEMA,
    CODE_SIGNATURES_SCHEMA,
    CODE_TYPE_DEFINITION_SCHEMA,
    _apply_workspace_edit,
    _check_lsp_reqs,
    _extract_md,
    _filter_diagnostics_in_range,
    _format_signatures,
    _handle_code_action,
    _handle_code_code_lens,
    _handle_code_completion,
    _handle_code_document_links,
    _handle_code_folding_range,
    _handle_code_implementations,
    _handle_code_inline_values,
    _handle_code_linked_editing,
    _handle_code_prepare_rename,
    _handle_code_selection_range,
    _handle_code_semantic_tokens,
    _handle_code_signatures,
    _handle_code_type_definition,
    _safe_register,
    _summarize_actions,
    code_action_tool,
    code_code_lens_tool,
    code_completion_tool,
    code_document_links_tool,
    code_folding_range_tool,
    code_implementations_tool,
    code_inline_values_tool,
    code_linked_editing_tool,
    code_prepare_rename_tool,
    code_selection_range_tool,
    code_semantic_tokens_tool,
    code_signatures_tool,
    code_type_definition_tool,
)
from .tools_handler import (
    CODE_FORMAT_SCHEMA,
    CODE_HOVER_SCHEMA,
    CODE_RENAME_SCHEMA,
    CODE_WORKSPACE_SYMBOLS_SCHEMA,
    _handle_code_call_hierarchy,
    _handle_code_callees,
    _handle_code_callers,
    _handle_code_definition,
    _handle_code_diagnostics,
    _handle_code_document_symbols,
    _handle_code_format,
    _handle_code_highlight,
    _handle_code_hover,
    _handle_code_inlay_hints,
    _handle_code_references,
    _handle_code_rename,
    _handle_code_type_hierarchy,
    _handle_code_workspace_symbols,
    _normalize_hover_contents,
    _try_cli_formatter,
    _wss_find_anchor_file,
    _wss_format_symbol_results,
    code_format_tool,
    code_hover_tool,
    code_rename_tool,
    code_workspace_symbols_tool,
)

# __all__ for backward compat with lsp_bridge.py `from .lsp.tools import *`
__all__ = [
    "code_definition_tool", "code_highlight_tool", "code_inlay_hints_tool",
    "code_document_symbols_tool", "code_references_tool", "code_diagnostics_tool",
    "_pull_lsp_diagnostics", "_resolve_target_and_lang",
    "_try_lsp_callers", "_fallback_reference_callers",
    "code_callers_tool", "code_callees_tool",
    "code_call_hierarchy_tool", "code_type_hierarchy_tool",
    "_auto_detect_paren_column", "_auto_detect_identifier_column",
    "_ast_fallback_definition", "_import_detect_language",
    "_extract_identifier", "_rg_search", "_ast_fallback_references",
    "_read_file_safe", "_python_ast_analyze",
    "_build_unused_import_diags", "_tsjs_import_heuristic",
    "_format_diagnostics_result", "_ast_fallback_diagnostics",
    "_ast_fallback_callees", "_extract_python_callees",
    "_extract_ts_callees", "_format_definitions", "_format_references",
    "code_workspace_symbols_tool", "code_rename_tool",
    "code_hover_tool", "code_format_tool", "code_signatures_tool",
    "code_action_tool", "code_type_definition_tool",
    "code_implementations_tool", "code_completion_tool",
    "code_code_lens_tool", "code_folding_range_tool",
    "code_selection_range_tool", "code_linked_editing_tool",
    "code_prepare_rename_tool", "code_semantic_tokens_tool",
    "code_document_links_tool", "code_inline_values_tool",
    "_check_lsp_reqs", "_safe_register",
    "_extract_md", "_format_signatures",
    "_apply_workspace_edit", "_filter_diagnostics_in_range",
    "_summarize_actions", "_normalize_hover_contents",
    "_try_cli_formatter", "_wss_find_anchor_file",
    "_wss_format_symbol_results",
    # Handlers
    "_handle_code_highlight", "_handle_code_inlay_hints",
    "_handle_code_type_hierarchy", "_handle_code_call_hierarchy",
    "_handle_code_document_symbols", "_handle_code_definition",
    "_handle_code_references", "_handle_code_diagnostics",
    "_handle_code_callers", "_handle_code_callees",
    "_handle_code_workspace_symbols", "_handle_code_rename",
    "_handle_code_hover", "_handle_code_format",
    "_handle_code_type_definition", "_handle_code_implementations",
    "_handle_code_signatures", "_handle_code_action",
    "_handle_code_completion", "_handle_code_code_lens",
    "_handle_code_folding_range", "_handle_code_selection_range",
    "_handle_code_linked_editing", "_handle_code_prepare_rename",
    "_handle_code_semantic_tokens", "_handle_code_document_links",
    "_handle_code_inline_values",
    # Schemas
    "CODE_HIGHLIGHT_SCHEMA", "CODE_INLAY_HINTS_SCHEMA",
    "CODE_TYPE_HIERARCHY_SCHEMA", "CODE_CALL_HIERARCHY_SCHEMA",
    "CODE_DOCUMENT_SYMBOLS_SCHEMA", "CODE_DEFINITION_SCHEMA",
    "CODE_REFERENCES_SCHEMA", "CODE_DIAGNOSTICS_SCHEMA",
    "CODE_CALLERS_SCHEMA", "CODE_CALLEES_SCHEMA",
    "CODE_WORKSPACE_SYMBOLS_SCHEMA", "CODE_RENAME_SCHEMA",
    "CODE_HOVER_SCHEMA", "CODE_FORMAT_SCHEMA",
    "CODE_TYPE_DEFINITION_SCHEMA", "CODE_IMPLEMENTATIONS_SCHEMA",
    "CODE_SIGNATURES_SCHEMA", "CODE_ACTION_SCHEMA",
    "CODE_COMPLETION_SCHEMA", "CODE_CODE_LENS_SCHEMA",
    "CODE_FOLDING_RANGE_SCHEMA", "CODE_SELECTION_RANGE_SCHEMA",
    "CODE_LINKED_EDITING_SCHEMA", "CODE_PREPARE_RENAME_SCHEMA",
    "CODE_SEMANTIC_TOKENS_SCHEMA", "CODE_DOCUMENT_LINKS_SCHEMA",
    "CODE_INLINE_VALUES_SCHEMA",
]
